;;; test-projects-multi-view.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(defmacro load! (&rest _) nil)
(defmacro after! (&rest body) `(progn ,@(cdr body)))
(defmacro use-package! (&rest _) nil)
(defmacro map! (&rest _) nil)
(defmacro add-hook! (&rest _) nil)
(defmacro undefine-key! (&rest _) nil)
(defmacro set-popup-rule! (&rest _) nil)
(defmacro defadvice! (&rest _) nil)

(defvar doom-data-dir temporary-file-directory)

(defun evil-set-initial-state (&rest _) nil)
(defun my/vterm-resize-log (&rest _) nil)
(defun my/vterm-size-refresh (&rest _) nil)
(defun +doom-dashboard-reload (&rest _) nil)

(load-file (expand-file-name "projects.el" (if load-file-name (file-name-directory load-file-name) default-directory)))
(remove-hook 'kill-emacs-hook #'projects-save)

(defun projects-test--reset-state ()
  (setq projects--current nil)
  (clrhash projects--table)
  (dolist (win (window-list nil 0))
    (set-window-parameter win 'projects-project nil))
  (set-frame-parameter nil 'projects-current nil)
  (set-frame-parameter nil 'projects-view-mode nil)
  (set-frame-parameter nil 'projects-multi-layout nil))

(defun projects-test--put-project (name dir)
  (puthash name (list :dir dir :buffers nil :files nil :switch-time 0)
           projects--table))

(ert-deftest projects-multi-view-entering-sets-frame-mode-and-layout ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 2)
  (should (eq (frame-parameter nil 'projects-view-mode) 'multi-project))
  (should (= (frame-parameter nil 'projects-multi-layout) 2))
  (should (= (length (window-list nil 0)) 2))
  (should (equal (window-parameter (selected-window) 'projects-project) "alpha")))

(ert-deftest projects-multi-view-leaving-promotes-selected-window-project ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 2)
  (let ((target (next-window)))
    (set-window-parameter target 'projects-project "beta")
    (select-window target)
    (projects-enter-single-project-view)
    (should (eq (frame-parameter nil 'projects-view-mode) 'single-project))
    (should (equal (projects-current) "beta"))))

(ert-deftest projects-multi-view-builds-four-window-grid ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects-test--put-project "gamma" "/tmp/gamma/")
  (projects-test--put-project "delta" "/tmp/delta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 4)
  (should (= (length (window-list nil 0)) 4))
  (should (equal (sort (mapcar (lambda (win) (window-parameter win 'projects-project))
                               (window-list nil 0))
                       #'string<)
                 '("alpha" "beta" "delta" "gamma"))))

(ert-deftest projects-multi-view-reuses-projects-when-layout-exceeds-project-count ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 4)
  (let ((projects (mapcar (lambda (win) (window-parameter win 'projects-project))
                          (window-list nil 0))))
    (should (= (length projects) 4))
    (should (equal (sort (delete-dups (copy-sequence projects)) #'string<)
                   '("alpha" "beta")))))
