;;; test-projects-multi-view.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(defmacro load! (&rest _) nil)
(defmacro after! (&rest body) `(progn ,@(cdr body)))
(defmacro use-package! (&rest _) nil)
(defmacro map! (&rest _) nil)
(defmacro add-hook! (&rest _) nil)
(defmacro undefine-key! (&rest _) nil)
(defmacro set-popup-rule! (&rest _) nil)
(defmacro defadvice! (&rest _) nil)

(defvar doom-data-dir temporary-file-directory)

(defun evil-set-initial-state (&rest _) nil)
(defun my/vterm-resize-log (&rest _) nil)
(defun my/vterm-size-refresh (&rest _) nil)
(defun +doom-dashboard-reload (&rest _) nil)

(load-file (expand-file-name "projects.el" (if load-file-name (file-name-directory load-file-name) default-directory)))
(remove-hook 'kill-emacs-hook #'projects-save)

(defun projects-test--reset-state ()
  (setq projects--current nil)
  (clrhash projects--table)
  (dolist (win (window-list nil 0))
    (set-window-parameter win 'projects-project nil))
  (set-frame-parameter nil 'projects-current nil)
  (set-frame-parameter nil 'projects-view-mode nil)
  (set-frame-parameter nil 'projects-multi-layout nil))

(defun projects-test--put-project (name dir)
  (puthash name (list :dir dir :buffers nil :files nil :switch-time 0)
           projects--table))

(ert-deftest projects-multi-view-entering-sets-frame-mode-and-layout ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 2)
  (should (eq (frame-parameter nil 'projects-view-mode) 'multi-project))
  (should (= (frame-parameter nil 'projects-multi-layout) 2))
  (should (= (length (window-list nil 0)) 2))
  (should (equal (window-parameter (selected-window) 'projects-project) "alpha")))

(ert-deftest projects-multi-view-leaving-promotes-selected-window-project ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 2)
  (let ((target (next-window)))
    (set-window-parameter target 'projects-project "beta")
    (select-window target)
    (projects-enter-single-project-view)
    (should (eq (frame-parameter nil 'projects-view-mode) 'single-project))
    (should (equal (projects-current) "beta"))))

(ert-deftest projects-multi-view-builds-four-window-grid ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects-test--put-project "gamma" "/tmp/gamma/")
  (projects-test--put-project "delta" "/tmp/delta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 4)
  (should (= (length (window-list nil 0)) 4))
  (should (equal (sort (mapcar (lambda (win) (window-parameter win 'projects-project))
                               (window-list nil 0))
                       #'string<)
                 '("alpha" "beta" "delta" "gamma"))))

(ert-deftest projects-multi-view-reuses-projects-when-layout-exceeds-project-count ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (delete-other-windows)
  (projects-enter-multi-project-view 4)
  (let ((projects (mapcar (lambda (win) (window-parameter win 'projects-project))
                          (window-list nil 0))))
    (should (= (length projects) 4))
    (should (equal (sort (delete-dups (copy-sequence projects)) #'string<)
                   '("alpha" "beta")))))

(ert-deftest projects-multi-view-switch-buffer-uses-selected-window-project ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (let ((alpha-buffer (get-buffer-create "alpha.txt"))
        (beta-buffer (get-buffer-create "beta.txt")))
    (with-current-buffer alpha-buffer (setq-local projects--buffer-project "alpha"))
    (with-current-buffer beta-buffer (setq-local projects--buffer-project "beta"))
    (projects-register-buffer alpha-buffer "alpha")
    (projects-register-buffer beta-buffer "beta")
    (projects--set-current "alpha")
    (projects-enter-multi-project-view 2)
    (let ((target (next-window)))
      (set-window-parameter target 'projects-project "beta")
      (select-window target)
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt collection &rest _)
                   (should (equal collection '("beta.txt")))
                   "beta.txt")))
        (projects-switch-buffer)))))

(ert-deftest projects-multi-view-switch-project-updates-only-selected-window ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects-test--put-project "gamma" "/tmp/gamma/")
  (projects--set-current "alpha")
  (projects-enter-multi-project-view 2)
  (let ((left (selected-window))
        (right (next-window)))
    (set-window-parameter left 'projects-project "alpha")
    (set-window-parameter right 'projects-project "beta")
    (select-window right)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (&rest _) "gamma")))
      (projects-switch-dispatch)
      (should (equal (window-parameter right 'projects-project) "gamma"))
      (should (equal (window-parameter left 'projects-project) "alpha")))))

(ert-deftest projects-multi-view-register-buffer-uses-selected-window-project ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (projects-enter-multi-project-view 2)
  (let ((target (next-window))
        (buffer (get-buffer-create "new.txt")))
    (set-window-parameter target 'projects-project "beta")
    (select-window target)
    (projects-register-buffer buffer)
    (should (equal (buffer-local-value 'projects--buffer-project buffer) "beta"))))

(ert-deftest projects-multi-view-last-buffer-falls-back-to-project-info-buffer ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (let ((buffer (get-buffer-create "alpha-only.txt")))
    (with-current-buffer buffer
      (setq-local projects--buffer-project "alpha"))
    (projects-register-buffer buffer "alpha")
    (projects--set-current "alpha")
    (switch-to-buffer buffer)
    (projects-enter-multi-project-view 2)
    (set-window-parameter (selected-window) 'projects-project "alpha")
    (with-current-buffer buffer
      (projects--cleanup-dead-buffers))
    (projects--fix-windows-after-kill)
    (should (string= (buffer-name (window-buffer (selected-window)))
                     "*project: alpha*"))))

(ert-deftest projects-multi-view-header-line-reflects-selected-window ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (projects-enter-multi-project-view 2)
  (let ((left (selected-window))
        (right (next-window)))
    (set-window-parameter left 'projects-project "alpha")
    (set-window-parameter right 'projects-project "beta")
    (projects--refresh-window-project-headers)
    (should (equal (buffer-local-value 'header-line-format (window-buffer left))
                   '(:eval (projects--window-header-line))))
    (select-window right)
    (projects--refresh-window-project-headers)
    (should (equal (window-parameter right 'projects-project) "beta"))))

(ert-deftest projects-multi-view-hides-tab-bar-and-persists-layout ()
  (projects-test--reset-state)
  (projects-test--put-project "alpha" "/tmp/alpha/")
  (projects-test--put-project "beta" "/tmp/beta/")
  (projects--set-current "alpha")
  (projects-enter-multi-project-view 2)
  (should (= (frame-parameter nil 'tab-bar-lines) 0))
  (let ((saved nil))
    (cl-letf (((symbol-function 'with-temp-file)
               (lambda (_file &rest body)
                 (setq saved (eval `(progn ,@body)))))
              ((symbol-function 'prin1)
               (lambda (object &rest _) (setq saved object))))
      (projects-save)
      (should (eq (plist-get saved :view-mode) 'multi-project))
      (should (= (plist-get saved :multi-layout) 2)))))
