#!/bin/sh

QUIET=0
ARGS=$(getopt w:s:g:bq $*)
set -- $ARGS
for i; do
    case "$i" in
        -w)
	    WALLET=$2
            shift; shift;;
	-v)
	    OSWALLET_ARGS+=" -v"
            shift;;
	-q)
	    QUIET=1
	    OSWALLET_ARGS+=" -q"
	    shift;;
	-s)
	    MODE="set"
	    USER=$2
	    OSWALLET_ARGS+=" -s $2"
	    shift; shift;;
	-g)
	    MODE="get"
	    USER=$2
	    OSWALLET_ARGS+=" -g $2"
	    shift; shift;;
	-b)
	    MODE="srv"
	    shift;;
        --)
            shift; break;;
    esac
done

OS=$(uname)
if [ "$OS" = "Darwin" ]; then
    if [ "$MODE" = "get" ]; then
	if [ $QUIET -lt 1 ]; then
	    security find-generic-password -s $WALLET -a $USER -g 2>&1 | grep password: | perl -ne 'print substr $_, 11, length($_)-13; print "\n"'
	fi
    else
	if [ $QUIET -lt 1 ]; then
	    echo "not supported on OS X"
	    oswallet
	    exit 1
	fi
    fi
else
    oswallet -w $WALLET $OSWALLET_ARGS
fi
